GET http://localhost:3000/transactions?searchText=798&selectedMonth=03
###

GET http://localhost:3000/statistics?selectedMonth=09
###

GET http://localhost:3000/bar-chart?selectedMonth=11
###

GET http://localhost:3000/combined-data?searchText&page=0&perPage=10&selectedMonth=05
###

